#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/pa2q

PRODUCT_COPY_FILES += \
    vendor/samsung/pa2q/proprietary/vendor/etc/LVACFS_Calibration.dat:$(TARGET_COPY_OUT_VENDOR)/etc/LVACFS_Calibration.dat \
    vendor/samsung/pa2q/proprietary/vendor/etc/LVACFS_Configuration.txt:$(TARGET_COPY_OUT_VENDOR)/etc/LVACFS_Configuration.txt \
    vendor/samsung/pa2q/proprietary/vendor/etc/LVACFS_ControlParams.txt:$(TARGET_COPY_OUT_VENDOR)/etc/LVACFS_ControlParams.txt \
    vendor/samsung/pa2q/proprietary/vendor/etc/SoundBoosterParam.txt:$(TARGET_COPY_OUT_VENDOR)/etc/SoundBoosterParam.txt \
    vendor/samsung/pa2q/proprietary/vendor/etc/audio/sku_sun/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_sun/mixer_paths.xml \
    vendor/samsung/pa2q/proprietary/vendor/etc/audio/sku_sun/resourcemanager.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_sun/resourcemanager.xml \
    vendor/samsung/pa2q/proprietary/vendor/etc/display/qdcm_calib_data_PA2_S6E3HAF_AMB666FM03.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_PA2_S6E3HAF_AMB666FM03.json \
    vendor/samsung/pa2q/proprietary/vendor/etc/libese-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libese-nxp.conf \
    vendor/samsung/pa2q/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/samsung/pa2q/proprietary/vendor/etc/nfc/libnfc-nxp_RF.conf:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/libnfc-nxp_RF.conf \
    vendor/samsung/pa2q/proprietary/vendor/etc/powerhint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/powerhint.xml \
    vendor/samsung/pa2q/proprietary/vendor/etc/secnvm/k250a_47000400_0.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_47000400_0.img \
    vendor/samsung/pa2q/proprietary/vendor/etc/secnvm/k250a_47000403_1.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_47000403_1.img \
    vendor/samsung/pa2q/proprietary/vendor/etc/secnvm/k250a_47000407_c.img:$(TARGET_COPY_OUT_VENDOR)/etc/secnvm/k250a_47000407_c.img \
    vendor/samsung/pa2q/proprietary/vendor/etc/sensors/config/akmlib.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/akmlib.json \
    vendor/samsung/pa2q/proprietary/vendor/etc/sensors/config/json.lst:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/json.lst \
    vendor/samsung/pa2q/proprietary/vendor/etc/sensors/config/pakala_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_ak991x_0.json \
    vendor/samsung/pa2q/proprietary/vendor/etc/sensors/config/pakala_ak991x_4.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_ak991x_4.json \
    vendor/samsung/pa2q/proprietary/vendor/etc/sensors/config/pakala_lps22df_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_lps22df_0.json \
    vendor/samsung/pa2q/proprietary/vendor/etc/sensors/config/pakala_lsm6dsv_0_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_lsm6dsv_0_0.json \
    vendor/samsung/pa2q/proprietary/vendor/etc/sensors/config/lsm6dsv_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dsv_0.json \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b00 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b01 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b02 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b03 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b04 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b05 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b06 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b07 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b08 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b09 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b10 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b11 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b12 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b13 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b14 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b15 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b16 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b17 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b18 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b19 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b20 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mbn \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mdt \
    vendor/samsung/pa2q/proprietary/vendor/firmware/CAMERA_ICP_170.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP_170.elf \
    vendor/samsung/pa2q/proprietary/vendor/firmware/Data.msc:$(TARGET_COPY_OUT_VENDOR)/firmware/Data.msc \
    vendor/samsung/pa2q/proprietary/vendor/firmware/PA2_S6E3HAF_AMB666FM01.dat:$(TARGET_COPY_OUT_VENDOR)/firmware/PA2_S6E3HAF_AMB666FM01.dat \
    vendor/samsung/pa2q/proprietary/vendor/firmware/PA2_S6E3HAF_AMB666FM03.dat:$(TARGET_COPY_OUT_VENDOR)/firmware/PA2_S6E3HAF_AMB666FM03.dat \
    vendor/samsung/pa2q/proprietary/vendor/firmware/SoundBoosterParam.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SoundBoosterParam.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/bt_nvm_loading.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/bt_nvm_loading.xml \
    vendor/samsung/pa2q/proprietary/vendor/firmware/cs35l43-bot-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l43-bot-dsp1-spk-prot.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/cs35l43-bot-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l43-bot-dsp1-spk-prot.wmfw \
    vendor/samsung/pa2q/proprietary/vendor/firmware/cs35l43-rcv-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l43-rcv-dsp1-spk-prot.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/cs35l43-rcv-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l43-rcv-dsp1-spk-prot.wmfw \
    vendor/samsung/pa2q/proprietary/vendor/firmware/cs40l26-a2h.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-a2h.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/cs40l26-calib.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-calib.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/cs40l26-calib.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-calib.wmfw \
    vendor/samsung/pa2q/proprietary/vendor/firmware/cs40l26-dvl.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-dvl.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/cs40l26-svc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/cs40l26-svc1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc1.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/cs40l26-svc2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc2.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/cs40l26-svc3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc3.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/cs40l26-wt1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-wt1.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/cs40l26-wt2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-wt2.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/cs40l26-wt3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-wt3.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/cs40l26.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/cs40l26.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26.wmfw \
    vendor/samsung/pa2q/proprietary/vendor/firmware/dax_param.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dax_param.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b00 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b01 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b02 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b03 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b04 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b05 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b06 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b07 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b08 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b09 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b10 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b11 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b12 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b13 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b14 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b15 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b16 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b17 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b18 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b19 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mbn \
    vendor/samsung/pa2q/proprietary/vendor/firmware/evass.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mdt \
    vendor/samsung/pa2q/proprietary/vendor/firmware/gen70900_aqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_aqe.fw \
    vendor/samsung/pa2q/proprietary/vendor/firmware/gen70900_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_sqe.fw \
    vendor/samsung/pa2q/proprietary/vendor/firmware/gen70900_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_zap.mbn \
    vendor/samsung/pa2q/proprietary/vendor/firmware/gmu_gen70900.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gmu_gen70900.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/hmtbtfw20.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/hmtbtfw20.tlv \
    vendor/samsung/pa2q/proprietary/vendor/firmware/hmtnv20.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/hmtnv20.b20 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/hmtnv20.b39:$(TARGET_COPY_OUT_VENDOR)/firmware/hmtnv20.b39 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/hmtnv20.b3c:$(TARGET_COPY_OUT_VENDOR)/firmware/hmtnv20.b3c \
    vendor/samsung/pa2q/proprietary/vendor/firmware/kiwi/amss20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/amss20.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/kiwi/bdwlan.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/bdwlan.elf \
    vendor/samsung/pa2q/proprietary/vendor/firmware/kiwi/bdwlan.elf1:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/bdwlan.elf1 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/kiwi/bdwlan.elf10:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/bdwlan.elf10 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/kiwi/bdwlan.elf2:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/bdwlan.elf2 \
    vendor/samsung/pa2q/proprietary/vendor/firmware/kiwi/phy_ucode20.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/phy_ucode20.elf \
    vendor/samsung/pa2q/proprietary/vendor/firmware/kiwi/qdss_trace_config_v2.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/qdss_trace_config_v2.cfg \
    vendor/samsung/pa2q/proprietary/vendor/firmware/kiwi/regdb.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/regdb.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/max77775-extra-fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/max77775-extra-fw.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/max77775-fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/max77775-fw.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/mfc/mfc_fw_flash_cps4038.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc/mfc_fw_flash_cps4038.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/ss_dsi_panel_PBA_BOOTING_FHD.dat:$(TARGET_COPY_OUT_VENDOR)/firmware/ss_dsi_panel_PBA_BOOTING_FHD.dat \
    vendor/samsung/pa2q/proprietary/vendor/firmware/tsp_synaptics/s3916t_pa2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tsp_synaptics/s3916t_pa2.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/uwb/libsr200t_dev_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/uwb/libsr200t_dev_fw.bin \
    vendor/samsung/pa2q/proprietary/vendor/firmware/uwb/libsr200t_prod_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/uwb/libsr200t_prod_fw.so \
    vendor/samsung/pa2q/proprietary/vendor/firmware/vpu35_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu35_4v.mbn \
    vendor/samsung/pa2q/proprietary/vendor/firmware/vpu35_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu35_4v_unsigned.mbn \
    vendor/samsung/pa2q/proprietary/vendor/firmware/vpu33_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu33_4v.mbn \
    vendor/samsung/pa2q/proprietary/vendor/firmware/vpu33_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu33_4v_unsigned.mbn \
    vendor/samsung/pa2q/proprietary/vendor/firmware/wlan-connection-roaming-backup.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan-connection-roaming-backup.ini \
    vendor/samsung/pa2q/proprietary/vendor/firmware/wlan-connection-roaming.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan-connection-roaming.ini \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n52.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n52.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n53.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n53.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n02.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n02.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n03.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n03.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n04.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n04.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n06.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n06.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n07.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n07.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n08.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n08.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n09.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n09.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n10.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n10.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n11.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n11.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n12.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n12.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n13.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n13.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n14.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n14.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n15.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n15.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n28.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n28.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n29.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n29.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n30.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n30.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n31.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n31.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n32.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n32.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n33.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n33.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n34.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n34.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n36.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n36.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n37.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n37.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n38.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n38.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n39.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n39.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n40.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n40.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n43.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n43.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n44.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n44.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n45.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n45.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n46.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n46.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n47.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n47.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n48.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n48.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n49.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n49.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n50.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n50.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n51.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n51.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n52.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n52.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n53.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n53.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n54.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n54.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n55.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n55.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n63.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n63.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n64.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n64.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n65.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n65.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n66.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n66.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n67.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n67.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n68.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n68.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n69.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n69.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n70.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n70.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n71.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n71.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n72.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n72.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n73.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n73.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n74.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n74.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n75.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n75.bin \
    vendor/samsung/pa2q/proprietary/vendor/lib64/bm5a79v08s13n76.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n76.bin \
